"use client";
import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { usePathname } from "next/navigation";
import { Provider } from "react-redux";
import store from "@/redux/store";
// import store from '@/app/redux/store';

const mulish = Mulish({
  weight: ["700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

function getPageTitle(pathname: string): string {
  switch (pathname) {
    case "/":
      return "Home";
    case "/about":
      return " About";
    case "/contact":
      return "Contact";
    case "/movies":
      return "Movies";
    // Add more cases for other pages as needed
    default:
      return "Home";
  }
}
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
console.log('store',store)

export default function RootLayout({
  children,
  title,
}: {
  children: React.ReactNode;
  title: string; // Add a title prop
}) {
  const currentPath = usePathname();

  const pageTitle = getPageTitle(currentPath);
  return (
    <html lang="en" className={mulish.className}>
      <head>
        <title>{"Netflix"+ "/" +pageTitle}</title>
      </head>
      <body>
        <Provider store={store}>
          <Header {...{pageTitle}}/>
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
